import type { Project } from './types';

export const createDefaultProject = (): Project => ({
  id: 'level-1',
  name: 'Level 1',
  displayName: 'Level 1',
  locationType: 'temple',
  grid: { width: 42, height: 34, cellSize: 1 },
  theme: 'dread_stone_black',
  rooms: [
    {
      id: 'R01',
      label: 'Reliquary',
      x: 16,
      z: 3,
      width: 9,
      depth: 8,
      type: 'room',
      tags: ['sanctum'],
      floorTexture: 'floor_worn_stone_01',
      encounterWeight: 1,
      safeForSpawn: false,
      userData: {},
    },
    {
      id: 'R02',
      label: 'West Guard Room',
      x: 3,
      z: 13,
      width: 10,
      depth: 8,
      type: 'room',
      tags: ['guard'],
      floorTexture: 'floor_worn_stone_01',
      encounterWeight: 2,
      safeForSpawn: true,
      userData: {},
    },
    {
      id: 'R03',
      label: 'East Stores',
      x: 27,
      z: 13,
      width: 10,
      depth: 7,
      type: 'room',
      tags: ['stores'],
      floorTexture: 'floor_worn_stone_01',
      encounterWeight: 1,
      safeForSpawn: true,
      userData: {},
    },
    {
      id: 'R04',
      label: 'Lower Hall',
      x: 12,
      z: 23,
      width: 16,
      depth: 7,
      type: 'room',
      tags: ['hall'],
      floorTexture: 'floor_worn_stone_01',
      encounterWeight: 2,
      safeForSpawn: true,
      userData: {},
    },
    {
      id: 'R05',
      label: 'Exit Cell',
      x: 34,
      z: 22,
      width: 6,
      depth: 4,
      type: 'room',
      tags: ['exit'],
      floorTexture: 'floor_worn_stone_01',
      encounterWeight: 0,
      safeForSpawn: false,
      userData: {},
    },
  ],
  corridors: [
    {
      id: 'C01',
      label: 'Central Spine',
      x: 18,
      z: 10,
      width: 5,
      depth: 14,
      type: 'corridor',
      tags: ['connector'],
      floorTexture: 'floor_worn_stone_01',
      encounterWeight: 0,
      safeForSpawn: false,
      userData: {},
    },
    {
      id: 'C02',
      label: 'West Link',
      x: 12,
      z: 16,
      width: 7,
      depth: 4,
      type: 'corridor',
      tags: ['connector'],
      floorTexture: 'floor_worn_stone_01',
      encounterWeight: 0,
      safeForSpawn: false,
      userData: {},
    },
    {
      id: 'C03',
      label: 'East Link',
      x: 23,
      z: 16,
      width: 5,
      depth: 4,
      type: 'corridor',
      tags: ['connector'],
      floorTexture: 'floor_worn_stone_01',
      encounterWeight: 0,
      safeForSpawn: false,
      userData: {},
    },
    {
      id: 'C04',
      label: 'Exit Link',
      x: 28,
      z: 22,
      width: 7,
      depth: 3,
      type: 'corridor',
      tags: ['connector'],
      floorTexture: 'floor_worn_stone_01',
      encounterWeight: 0,
      safeForSpawn: false,
      userData: {},
    },
    {
      id: 'C05',
      label: 'Entry Stair',
      x: 17,
      z: 29,
      width: 6,
      depth: 5,
      type: 'corridor',
      tags: ['connector', 'entry'],
      floorTexture: 'floor_worn_stone_01',
      encounterWeight: 0,
      safeForSpawn: true,
      userData: {},
    },
  ],
  doors: [
    {
      id: 'D01',
      fromRoom: 'R01',
      toRoom: 'C01',
      x: 20,
      z: 10,
      width: 2,
      kind: 'door',
      tags: ['doorway'],
      userData: {},
    },
    {
      id: 'D02',
      fromRoom: 'R02',
      toRoom: 'C02',
      x: 13,
      z: 18,
      width: 1,
      kind: 'lockedDoor',
      tags: ['doorway', 'locked'],
      userData: {},
    },
    {
      id: 'D03',
      fromRoom: 'R03',
      toRoom: 'C03',
      x: 27,
      z: 18,
      width: 1,
      kind: 'secretDoor',
      tags: ['doorway', 'secret'],
      userData: {},
    },
    {
      id: 'D04',
      fromRoom: 'R04',
      toRoom: 'C01',
      x: 20,
      z: 23,
      width: 2,
      kind: 'doubleDoor',
      tags: ['doorway'],
      userData: {},
    },
    {
      id: 'D05',
      fromRoom: 'R05',
      toRoom: 'C04',
      x: 35,
      z: 23,
      width: 1,
      kind: 'door',
      tags: ['doorway'],
      userData: {},
    },
  ],
  placements: [
    {
      id: 'L01',
      kind: 'torch',
      roomId: 'R01',
      x: 18,
      z: 6,
      y: 1.5,
      rotationY: 0,
      category: 'light',
      dimensions: { width: 0.35, depth: 0.35, height: 1.8 },
      tags: ['wall-mounted'],
      userData: {},
    },
    {
      id: 'L02',
      kind: 'wallSconce',
      roomId: 'R03',
      x: 28,
      z: 18,
      y: 1.5,
      rotationY: 0,
      category: 'light',
      dimensions: { width: 0.4, depth: 0.25, height: 1.6 },
      tags: ['wall-mounted'],
      userData: {},
    },
    {
      id: 'E01',
      kind: 'enemySpawn',
      roomId: 'R05',
      x: 36,
      z: 24,
      y: 0,
      rotationY: 0,
      category: 'enemies',
      dimensions: { width: 1, depth: 1 },
      tags: ['skeleton'],
      userData: { encounter: 'sentinel' },
    },
    {
      id: 'O01',
      kind: 'chest',
      roomId: 'R03',
      x: 33,
      z: 15,
      y: 0,
      rotationY: 0,
      category: 'objects',
      dimensions: { width: 1.2, depth: 0.8, height: 0.8 },
      tags: ['blocking'],
      userData: {},
    },
    {
      id: 'P01',
      kind: 'playerSpawn',
      roomId: 'R04',
      x: 23,
      z: 27,
      y: 0,
      rotationY: 0,
      category: 'stairs',
      dimensions: { width: 1, depth: 1 },
      tags: ['start'],
      userData: {},
    },
    {
      id: 'N01',
      kind: 'note',
      roomId: 'R01',
      x: 20,
      z: 7,
      y: 0,
      rotationY: 0,
      category: 'decor',
      dimensions: { width: 1, depth: 1 },
      tags: ['lore'],
      userData: { note: 'A cold sigil is carved into the central stone.' },
    },
  ],
  layers: {
    structure: { visible: true, locked: false },
    doors: { visible: true, locked: false },
    lighting: { visible: true, locked: false },
    enemies: { visible: true, locked: false },
    objects: { visible: true, locked: false },
    notes: { visible: true, locked: false },
  },
  notes: ['Default sample inspired by the Dread Stone Black prototype map.'],
  metadata: {
    version: '1.0.0',
    themePreset: 'dread_stone_black',
    snap: true,
    zoom: 100,
    footprint: 'temple',
  },
});
