import type { Project } from '../editor/types';
import { exportDsbDefinition } from './exportDsbDefinition';
import { formatHealthSummary, getExportHealth } from './exportHealth';

const jsSlug = (value: string) => value.trim().toLowerCase().replace(/[^a-z0-9]+/g, '') || 'level1';

const listSection = (items: string[], emptyText: string) =>
  items.length > 0 ? items.map((item) => `- ${item}`).join('\n') : `- ${emptyText}`;

export const exportCodexHandoff = (project: Project) => {
  const filename = `${jsSlug(project.name)}.definition.js`;
  const targetPath = `src/game/locations/generated/${filename}`;
  const health = getExportHealth(project, exportDsbDefinition(project));

  return `# DDplus Handoff: ${project.displayName}

Generated by Dungeon Drawer Plus v1 for Dread Stone Black.

## Files

- Generated definition: \`${filename}\`
- Target path in Dread Stone Black: \`${targetPath}\`

## Registry Instructions

1. Place the generated definition file under \`src/game/locations/generated/\`.
2. Import it in \`src/game/locations/locationRegistry.js\`.
3. Add it to the \`locationDefinitions\` object using the generated definition's \`id\`.
4. Add field entrance/exit wiring only if requested.

## Validation Instructions

1. Run \`npm run validate:dungeons\`.
2. Run \`npm run build\`.
3. Fix only schema, registry, or export integration issues.
4. Do not redesign this map. It may be an intentional smoke test.

## Export Health

${formatHealthSummary(health).map((line) => `- ${line}`).join('\n')}

## Warnings

${listSection(health.warnings, 'No warnings reported.')}

## Errors

${listSection(health.errors, 'No errors reported.')}

## Notes

- DDplus v1 exports rectangle-authored rooms and corridors only.
- Corridors are room-like rectangles tagged \`connector\`.
- Props with collision use \`collisionRef\` pointing to generated blockers.
- Door \`wallGaps\` are generated per connected room/corridor. North/south wall doors span X; east/west wall doors span Z.
- Wall-mounted torch placements export as DSB \`torchFixtures\`.
- Free-standing light placements export as \`lights\`.
`;
};
