import type { Project } from '../editor/types';

export const exportCodexHandoff = (project: Project) => `# DDplus Handoff: ${project.displayName}

Generated by Dungeon Drawer Plus v1 for Dread Stone Black.

## Files

- Generated definition: \`level1.definition.js\`
- Target path in Dread Stone Black: \`src/game/locations/generated/level1.definition.js\`

## Codex Instructions

1. Place the generated definition file under \`src/game/locations/generated/\`.
2. Import it in \`src/game/locations/locationRegistry.js\`.
3. Add it to the \`locationDefinitions\` object.
4. Add field entrance/exit wiring only if requested.
5. Run \`npm run validate:dungeons\`.
6. Run \`npm run build\`.
7. Fix only schema, registry, or export issues; do not redesign the dungeon.

## Blueprint Summary

- Grid: ${project.grid.width} x ${project.grid.height}
- Rooms: ${project.rooms.length}
- Corridors: ${project.corridors.length}
- Doors: ${project.doors.length}
- Placements: ${project.placements.length}
`;
